#List the number of films per category.

SELECT name, count(film_id)
FROM film

JOIN film_category
USING (film_id)

JOIN category
USING (category_id)

GROUP BY name;



#Retrieve the store ID, city, and country for each store.

SELECT store_id,city,country 
FROM country
JOIN city
USING (country_id )
JOIN address
USING (city_id )
JOIN store
USING (address_id)

GROUP BY store_id;


#Calculate the total revenue generated by each store in dollars.
SELECT SUM(amount)
FROM payment
JOIN customer
USING(customer_id)
JOIN store
USING (store_id)

GROUP BY store_id;

#SELECT length, film_id
#FROM film ;


#Determine the average running time of films for each category.
SELECT category.name, AVG(lenght)
FROM film
JOIN film_category
USING(film_id)
JOIN category
USING(category_id)

GROUP BY category.name













